---
title: "Save_annotations_for_Python_Loupe"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
#install.packages("BiocManager")
#BiocManager::install("Seurat")
#BiocManager::install("ggplot2")
#BiocManager::install("sctransform")

library(Seurat)
library(ggplot2)
library(dplyr)
library(ape)
library(cowplot)
library(Matrix)
library(EnhancedVolcano)
library(knitr)
library(readr)

#find out where you are
getwd()

#Specify where your matrix files are
dir= "/Users/whippoorwill/Desktop/Sequencing/LD_AVM02/"
datafolder = "Data/Seurat"
filename = "Microglia_BC_Macrophages_subset.RData"
organism = "Mouse"
defile = "Macrophage_only_all_markers.csv"
cellcyclefile = "https://raw.githubusercontent.com/lcdorman/scrnaseq/master/Spreadsheets/regev_lab_cell_cycle_genes.csv"

m = c("nCount_RNA","nFeature_RNA","percent.mito","percent.ribo")
Plotfolder = "Plots"
name = "Macrophage_subset"

if(organism == "Mouse"){library(org.Mm.eg.db)}
if(organism == "Human"){library(org.Hs.eg.db)}
if(organism == "Zebrafish"){library(org.Dr.eg.db)}
```

Load in your filtered dataset
```{r}
load(file.path(dir,datafolder,filename))
```

You can save umap and pc embeddings to load into other programs like Loupe and anything in Python like scvelo (velocity)
```{r}
#Edit name only if one project has multiple embeddings
name = paste0(Project(sobject),"_",name)
```


```{r}
#Save umap embeddings
umap =as.data.frame(sobject@reductions$umap@cell.embeddings)
umap$Cellname = rownames(umap)
umap = umap[,order(colnames(umap))]
write.csv(umap,file = file.path(dir,"Annotation",paste0(name,"_umap_embed.csv")),row.names = F)

#save pcs
pc =as.data.frame(sobject@reductions$pc@cell.embeddings)
pc$Cellname = rownames(pc)
pc = pc[,order(colnames(pc))]
write.csv(pc,file = file.path(dir,"Annotation",paste0(name,"_pc_embed.csv")),row.names = F)

#save metadata
meta = sobject@meta.data
meta$Cellname = rownames(meta)

#pick columns you want to keep
meta = meta[,c(1,2,3,4,5,7,8,9,10,12,14,15,25,26,27)]
#meta = meta[,c(ncol(meta),1:(ncol(meta)-1))]
write.csv(meta,file = file.path(dir,"Annotation",paste0(name,"_metadata.csv")),row.names = F)
write.csv(meta,file = "~/Desktop/Dorman_P7_metadata_clustering.csv",row.names = F)

#For PanoView (in Python, a way to mathematically validate # of clusters found)
annotation = sobject$sample_description #or any column
x = as.matrix(GetAssayData(sobject,slot = "counts"))
x = x[rownames(x) %in% VariableFeatures(sobject),]

write.csv(x,file = file.path(dir,"Annotation",paste0(name,"_counts.csv")))
write.csv(annotation,file = file.path(dir,"Annotation",paste0(name,"_annotation.csv")))

#Save counts
counts = GetAssayData(sobject,slot = "counts")
write.csv(counts,file = "~/Desktop/DormanP7Glia_counts.csv")

#save normalized counts
counts = GetAssayData(sobject,slot = "data")
write.csv(counts,file = "~/Desktop/Dorman_P7Glia_normalizedcounts.csv")


```